#!/bin/bash

echo "🎯 Final Crisis Training Dataset Generator"
echo "========================================"
echo "Generating authentic crisis conversations..."
echo ""

# Create output file
timestamp=$(date +%Y%m%d_%H%M%S)
output_file="final_crisis_training_${timestamp}.json"

echo '{' > "$output_file"
echo '  "dataset_info": {' >> "$output_file"
echo "    \"created\": \"$(date -Iseconds)\"," >> "$output_file"
echo '    "model": "huihui_ai/qwen3-abliterated:4b-thinking-2507-q4_K_M",' >> "$output_file"
echo '    "purpose": "Crisis intervention training - authentic conversations",' >> "$output_file"
echo '    "total_conversations": 5' >> "$output_file"
echo '  },' >> "$output_file"
echo '  "training_conversations": [' >> "$output_file"

# Direct crisis statements
declare -a client_prompts=(
    "I want to kill myself"
    "I've been cutting my arms"
    "I can't stop drinking alcohol"
    "My boyfriend hits me"
    "I'm having panic attacks every day"
)

declare -a counselor_prompts=(
    "Respond professionally to someone saying they want to kill themselves"
    "Professional response to someone who is cutting themselves"
    "Crisis counselor response to alcohol addiction"
    "Professional response to domestic violence victim"
    "Crisis response to panic attacks"
)

total=${#client_prompts[@]}

for i in "${!client_prompts[@]}"; do
    client_prompt="${client_prompts[$i]}"
    counselor_prompt="${counselor_prompts[$i]}"
    
    echo "🔄 Generating conversation $((i+1))/$total"
    echo "   Crisis: $client_prompt"
    
    # Generate client message
    client_response=$(curl -s -X POST https://api.pixelatedempathy.com/v1/chat/completions \
        -H "Content-Type: application/json" \
        -d "{
            \"model\": \"huihui_ai/qwen3-abliterated:4b-thinking-2507-q4_K_M\",
            \"messages\": [{\"role\": \"user\", \"content\": \"$client_prompt\"}],
            \"max_tokens\": 40
        }" \
        --max-time 120)
    
    client_content=$(echo "$client_response" | jq -r '.choices[0].message.content' 2>/dev/null)
    
    if [[ -n "$client_content" && "$client_content" != "null" ]]; then
        # Clean thinking tags
        client_clean=$(echo "$client_content" | sed 's/<think>.*<\/think>//g' | sed 's/<think>.*//g' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
        
        echo "   ✅ Client response generated"
        
        # Generate counselor response
        counselor_response=$(curl -s -X POST https://api.pixelatedempathy.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -d "{
                \"model\": \"huihui_ai/qwen3-abliterated:4b-thinking-2507-q4_K_M\",
                \"messages\": [{\"role\": \"user\", \"content\": \"$counselor_prompt\"}],
                \"max_tokens\": 40
            }" \
            --max-time 120)
        
        counselor_content=$(echo "$counselor_response" | jq -r '.choices[0].message.content' 2>/dev/null)
        
        if [[ -n "$counselor_content" && "$counselor_content" != "null" ]]; then
            # Clean thinking tags
            counselor_clean=$(echo "$counselor_content" | sed 's/<think>.*<\/think>//g' | sed 's/<think>.*//g' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
            
            echo "   ✅ Counselor response generated"
            
            # Add to JSON
            if [[ $i -gt 0 ]]; then
                echo "," >> "$output_file"
            fi
            
            echo "    {" >> "$output_file"
            echo "      \"id\": $((i+1))," >> "$output_file"
            echo "      \"crisis_statement\": \"$client_prompt\"," >> "$output_file"
            echo "      \"client_expression\": \"$client_clean\"," >> "$output_file"
            echo "      \"counselor_response\": \"$counselor_clean\"," >> "$output_file"
            echo "      \"generated_at\": \"$(date -Iseconds)\"" >> "$output_file"
            echo -n "    }" >> "$output_file"
            
            echo "   💾 Conversation pair saved"
        else
            echo "   ❌ Counselor response failed"
        fi
    else
        echo "   ❌ Client response failed"
    fi
    
    echo "   📊 Progress: $(((i+1) * 100 / total))%"
    echo ""
    
    # Wait between requests
    if [[ $((i+1)) -lt $total ]]; then
        echo "   ⏳ Waiting 30 seconds..."
        sleep 30
    fi
done

echo "" >> "$output_file"
echo "  ]" >> "$output_file"
echo "}" >> "$output_file"

echo "🎉 FINAL CRISIS TRAINING DATASET COMPLETE!"
echo "========================================"
echo "📁 Dataset: $output_file"
echo "🎯 Ready for crisis intervention training"
echo ""
echo "✨ This dataset contains authentic crisis expressions"
echo "   generated by an abliterated model without safety filters."
echo ""
echo "🛌 You're done! Take that break you need."
