#!/bin/bash
# Commands to run on VPS for setup

echo "=== VPS Setup Commands ==="
echo ""
echo "1. Navigate to training_ready directory:"
echo "   cd ~/training_ready/training_ready"
echo ""
echo "2. Read quick start guide:"
echo "   cat GET_UP_TO_SPEED.md"
echo ""
echo "3. Check Python environment:"
echo "   python3 --version"
echo "   which python3"
echo ""
echo "4. Install uv (if not installed):"
echo "   curl -LsSf https://astral.sh/uv/install.sh | sh"
echo "   source ~/.cargo/env  # or add to ~/.bashrc"
echo ""
echo "5. Install dependencies:"
echo "   ./install_dependencies.sh"
echo ""
echo "6. Configure AWS credentials:"
echo "   export AWS_ACCESS_KEY_ID='your-key'"
echo "   export AWS_SECRET_ACCESS_KEY='your-secret'"
echo "   export AWS_DEFAULT_REGION='us-east-1'"
echo "   export S3_BUCKET='your-bucket-name'"
echo ""
echo "7. Verify catalog:"
echo "   cat scripts/output/dataset_accessibility_catalog.json | python3 -m json.tool | head -20"
echo ""
echo "8. Download remote datasets to S3:"
echo "   python3 scripts/download_to_s3.py \\"
echo "     --bucket \$S3_BUCKET \\"
echo "     --catalog scripts/output/dataset_accessibility_catalog.json"
echo ""

