#!/bin/bash
# Quick reference commands for VPS setup

echo "=== VPS Training Ready - Quick Commands ==="
echo ""
echo "📍 Current location: /home/vivi/pixelated/ai/training_ready"
echo ""
echo "1. Install dependencies:"
echo "   cd /home/vivi/pixelated"
echo "   source ~/.zshrc"
echo "   uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu"
echo "   uv pip install boto3 datasets kaggle requests"
echo ""
echo "2. Verify installation:"
echo "   python3 -c 'import torch; print(\"torch:\", torch.__version__)'"
echo "   python3 -c 'import boto3; print(\"boto3:\", boto3.__version__)'"
echo ""
echo "3. Configure OVH object storage (S3-compatible):"
echo "   export OVH_S3_BUCKET=\"pixel-data\""
echo "   export OVH_S3_ENDPOINT=\"https://s3.us-east-va.io.cloud.ovh.us\""
echo "   export OVH_S3_REGION=\"us-east-va\""
echo "   export OVH_S3_ACCESS_KEY=\"your-ovh-access-key\""
echo "   export OVH_S3_SECRET_KEY=\"your-ovh-secret-key\""
echo "   export S3_BUCKET=\"\$OVH_S3_BUCKET\"  # for scripts that expect S3_BUCKET"
echo ""
echo "4. Check catalog:"
echo "   cd /home/vivi/pixelated/ai/training_ready"
echo "   python3 -c \"import json; d=json.load(open('scripts/output/dataset_accessibility_catalog.json')); print(f'Total: {d[\\\"summary\\\"][\\\"total\\\"]}, Local: {d[\\\"summary\\\"][\\\"local_only\\\"]}, HF: {d[\\\"summary\\\"][\\\"huggingface\\\"]}')\""
echo ""
echo "5. Download HuggingFace datasets to S3:"
echo "   cd /home/vivi/pixelated/ai/training_ready"
echo "   python3 scripts/download_to_s3.py \\"
echo "     --bucket \$S3_BUCKET \\"
echo "     --catalog scripts/output/dataset_accessibility_catalog.json"
echo ""
echo "6. Upload local-only datasets (from LOCAL machine):"
echo "   cd /home/vivi/pixelated"
echo "   aws s3 sync \\"
echo "     --exclude \"*\" \\"
echo "     --include-from ai/training_ready/scripts/output/local_only_upload_list.txt \\"
echo "     / \\"
echo "     s3://\$S3_BUCKET/datasets/local/"
echo ""

